In [1]:
# Import all necessary libraries.
import pandas as pd
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, roc_curve, auc
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
x_train = np.array(['Chinese Beijing Chinese',
                   'Chinese Chinese Shanghai',
                   'Chinese Macao',
                   'Tokyo Japan Chinese'])

y_train = np.array(['china','china','china','not china'])

x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

In [6]:
#bernoulli

vect = CountVectorizer(binary=True)

x_train_dtm = vect.fit_transform(x_train)

print(vect.get_feature_names())
print()
print(x_train_dtm.toarray())
print()

x_test_dtm = vect.transform(x_test)

print(x_test_dtm.toarray())
print()

model = BernoulliNB(binarize=None)

model.fit(x_train_dtm, y_train)

y_pred_class = model.predict(x_test_dtm)

print(y_pred_class)
print()

print(model.predict_proba(x_test_dtm))

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']

[[1 1 0 0 0 0]
 [0 1 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]

[[0 1 1 0 0 1]]

['not china']

[[0.19106679 0.80893321]]


In [7]:
#multinomial
x_train = np.array(['Chinese Beijing Chinese',
                   'Chinese Chinese Shanghai',
                   'Chinese Macao',
                   'Tokyo Japan Chinese'])

y_train = np.array(['china','china','china','not china'])

x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

vect = CountVectorizer()

x_train_dtm = vect.fit_transform(x_train)

print(vect.get_feature_names())
print()
print(x_train_dtm.toarray())
print()

x_test_dtm = vect.transform(x_test)

print(x_test_dtm.toarray())
print()

model = MultinomialNB()

model.fit(x_train_dtm, y_train)

y_pred_class = model.predict(x_test_dtm)

print(y_pred_class)
print()

print(model.predict_proba(x_test_dtm))

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']

[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]

[[0 3 1 0 0 1]]

['china']

[[0.68975861 0.31024139]]


O motivo da classificação de bernoulli é porque o vetor utilizado para testes é exatamente igual ao quarto vetor para treinamento, assim classificando-o como 'not-china' 

Já o motivo para a classificação do multinomial é porque aparece muitas vezes o indicador 'chinese'.